<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = array(
            array('id' => '1', 'iso' => 'AF', 'name' => 'أفغنستان', 'nicename' => 'Afghanistan', 'iso3' => 'AFG', 'numcode' => '4', 'phonecode' => '93'),
            array('id' => '2', 'iso' => 'AL', 'name' => 'ألبانيا', 'nicename' => 'Albania', 'iso3' => 'ALB', 'numcode' => '8', 'phonecode' => '355'),
            array('id' => '3', 'iso' => 'DZ', 'name' => 'الجزائر', 'nicename' => 'Algeria', 'iso3' => 'DZA', 'numcode' => '12', 'phonecode' => '213'),
            array('id' => '4', 'iso' => 'AS', 'name' => 'ساموا الأمريكية', 'nicename' => 'American Samoa', 'iso3' => 'ASM', 'numcode' => '16', 'phonecode' => '1684'),
            array('id' => '5', 'iso' => 'AD', 'name' => 'أندورا', 'nicename' => 'Andorra', 'iso3' => 'AND', 'numcode' => '20', 'phonecode' => '376'),
            array('id' => '6', 'iso' => 'AO', 'name' => 'أنغولا', 'nicename' => 'Angola', 'iso3' => 'AGO', 'numcode' => '24', 'phonecode' => '244'),
            array('id' => '7', 'iso' => 'AI', 'name' => 'أنغيلا', 'nicename' => 'Anguilla', 'iso3' => 'AIA', 'numcode' => '660', 'phonecode' => '1264'),
            array('id' => '8', 'iso' => 'AQ', 'name' => 'أنتاركتيكا', 'nicename' => 'Antarctica', 'iso3' => NULL, 'numcode' => NULL, 'phonecode' => '0'),
            array('id' => '9', 'iso' => 'AG', 'name' => 'أنتيغوا وبربودا', 'nicename' => 'Antigua and Barbuda', 'iso3' => 'ATG', 'numcode' => '28', 'phonecode' => '1268'),
            array('id' => '10', 'iso' => 'AR', 'name' => 'الأرجنتين', 'nicename' => 'Argentina', 'iso3' => 'ARG', 'numcode' => '32', 'phonecode' => '54'),
            array('id' => '11', 'iso' => 'AM', 'name' => 'أرمينيا', 'nicename' => 'Armenia', 'iso3' => 'ARM', 'numcode' => '51', 'phonecode' => '374'),
            array('id' => '12', 'iso' => 'AW', 'name' => 'أروبا', 'nicename' => 'Aruba', 'iso3' => 'ABW', 'numcode' => '533', 'phonecode' => '297'),
            array('id' => '13', 'iso' => 'AU', 'name' => 'أستراليا', 'nicename' => 'Australia', 'iso3' => 'AUS', 'numcode' => '36', 'phonecode' => '61'),
            array('id' => '14', 'iso' => 'AT', 'name' => 'النمسا', 'nicename' => 'Austria', 'iso3' => 'AUT', 'numcode' => '40', 'phonecode' => '43'),
            array('id' => '15', 'iso' => 'AZ', 'name' => 'أذربيجان', 'nicename' => 'Azerbaijan', 'iso3' => 'AZE', 'numcode' => '31', 'phonecode' => '994'),
            array('id' => '16', 'iso' => 'BS', 'name' => 'البهاما', 'nicename' => 'Bahamas', 'iso3' => 'BHS', 'numcode' => '44', 'phonecode' => '1242'),
            array('id' => '17', 'iso' => 'BH', 'name' => 'البحرين', 'nicename' => 'Bahrain', 'iso3' => 'BHR', 'numcode' => '48', 'phonecode' => '973'),
            array('id' => '18', 'iso' => 'BD', 'name' => 'بنغلاديش', 'nicename' => 'Bangladesh', 'iso3' => 'BGD', 'numcode' => '50', 'phonecode' => '880'),
            array('id' => '19', 'iso' => 'BB', 'name' => 'بربادوس', 'nicename' => 'Barbados', 'iso3' => 'BRB', 'numcode' => '52', 'phonecode' => '1246'),
            array('id' => '20', 'iso' => 'BY', 'name' => 'بيلاروسيا', 'nicename' => 'Belarus', 'iso3' => 'BLR', 'numcode' => '112', 'phonecode' => '375'),
            array('id' => '21', 'iso' => 'BE', 'name' => 'بلجيكا', 'nicename' => 'Belgium', 'iso3' => 'BEL', 'numcode' => '56', 'phonecode' => '32'),
            array('id' => '22', 'iso' => 'BZ', 'name' => 'بيليز', 'nicename' => 'Belize', 'iso3' => 'BLZ', 'numcode' => '84', 'phonecode' => '501'),
            array('id' => '23', 'iso' => 'BJ', 'name' => 'بنين', 'nicename' => 'Benin', 'iso3' => 'BEN', 'numcode' => '204', 'phonecode' => '229'),
            array('id' => '24', 'iso' => 'BM', 'name' => 'برمودا', 'nicename' => 'Bermuda', 'iso3' => 'BMU', 'numcode' => '60', 'phonecode' => '1441'),
            array('id' => '25', 'iso' => 'BT', 'name' => 'بوتان', 'nicename' => 'Bhutan', 'iso3' => 'BTN', 'numcode' => '64', 'phonecode' => '975'),
            array('id' => '26', 'iso' => 'BO', 'name' => 'بوليفيا', 'nicename' => 'Bolivia', 'iso3' => 'BOL', 'numcode' => '68', 'phonecode' => '591'),
            array('id' => '27', 'iso' => 'BA', 'name' => 'البوسنة والهرسك', 'nicename' => 'Bosnia and Herzegovina', 'iso3' => 'BIH', 'numcode' => '70', 'phonecode' => '387'),
            array('id' => '28', 'iso' => 'BW', 'name' => 'بوتسوانا', 'nicename' => 'Botswana', 'iso3' => 'BWA', 'numcode' => '72', 'phonecode' => '267'),
            array('id' => '29', 'iso' => 'BV', 'name' => 'جزيرة بوفيت', 'nicename' => 'Bouvet Island', 'iso3' => NULL, 'numcode' => NULL, 'phonecode' => '0'),
            array('id' => '30', 'iso' => 'BR', 'name' => 'البرازيل', 'nicename' => 'Brazil', 'iso3' => 'BRA', 'numcode' => '76', 'phonecode' => '55'),
            array('id' => '31', 'iso' => 'IO', 'name' => 'إقليم المحيط البريطاني الهندي', 'nicename' => 'British Indian Ocean Territory', 'iso3' => NULL, 'numcode' => NULL, 'phonecode' => '246'),
            array('id' => '32', 'iso' => 'BN', 'name' => 'بروناي دار السلام', 'nicename' => 'Brunei Darussalam', 'iso3' => 'BRN', 'numcode' => '96', 'phonecode' => '673'),
            array('id' => '33', 'iso' => 'BG', 'name' => 'بلغاريا', 'nicename' => 'Bulgaria', 'iso3' => 'BGR', 'numcode' => '100', 'phonecode' => '359'),
            array('id' => '34', 'iso' => 'BF', 'name' => 'بوركينا فاسو', 'nicename' => 'Burkina Faso', 'iso3' => 'BFA', 'numcode' => '854', 'phonecode' => '226'),
            array('id' => '35', 'iso' => 'BI', 'name' => 'بوروندي', 'nicename' => 'Burundi', 'iso3' => 'BDI', 'numcode' => '108', 'phonecode' => '257'),
            array('id' => '36', 'iso' => 'KH', 'name' => 'كمبوديا', 'nicename' => 'Cambodia', 'iso3' => 'KHM', 'numcode' => '116', 'phonecode' => '855'),
            array('id' => '37', 'iso' => 'CM', 'name' => 'الكاميرون', 'nicename' => 'Cameroon', 'iso3' => 'CMR', 'numcode' => '120', 'phonecode' => '237'),
            array('id' => '38', 'iso' => 'CA', 'name' => 'كندا', 'nicename' => 'Canada', 'iso3' => 'CAN', 'numcode' => '124', 'phonecode' => '1'),
            array('id' => '39', 'iso' => 'CV', 'name' => 'كيب فيردي', 'nicename' => 'Cape Verde', 'iso3' => 'CPV', 'numcode' => '132', 'phonecode' => '238'),
            array('id' => '40', 'iso' => 'KY', 'name' => 'جزر كايمان', 'nicename' => 'Cayman Islands', 'iso3' => 'CYM', 'numcode' => '136', 'phonecode' => '1345'),
            array('id' => '41', 'iso' => 'CF', 'name' => 'جمهورية افريقيا الوسطى', 'nicename' => 'Central African Republic', 'iso3' => 'CAF', 'numcode' => '140', 'phonecode' => '236'),
            array('id' => '42', 'iso' => 'TD', 'name' => 'تشاد', 'nicename' => 'Chad', 'iso3' => 'TCD', 'numcode' => '148', 'phonecode' => '235'),
            array('id' => '43', 'iso' => 'CL', 'name' => 'شيلي', 'nicename' => 'Chile', 'iso3' => 'CHL', 'numcode' => '152', 'phonecode' => '56'),
            array('id' => '44', 'iso' => 'CN', 'name' => 'الصين', 'nicename' => 'China', 'iso3' => 'CHN', 'numcode' => '156', 'phonecode' => '86'),
            array('id' => '45', 'iso' => 'CX', 'name' => 'جزيرة الكريسماس', 'nicename' => 'Christmas Island', 'iso3' => NULL, 'numcode' => NULL, 'phonecode' => '61'),
            array('id' => '46', 'iso' => 'CC', 'name' => 'جزر كوكوس (كيلينغ)', 'nicename' => 'Cocos (Keeling) Islands', 'iso3' => NULL, 'numcode' => NULL, 'phonecode' => '672'),
            array('id' => '47', 'iso' => 'CO', 'name' => 'كولومبيا', 'nicename' => 'Colombia', 'iso3' => 'COL', 'numcode' => '170', 'phonecode' => '57'),
            array('id' => '48', 'iso' => 'KM', 'name' => 'جزر القمر', 'nicename' => 'Comoros', 'iso3' => 'COM', 'numcode' => '174', 'phonecode' => '269'),
            array('id' => '49', 'iso' => 'CG', 'name' => 'الكونغو', 'nicename' => 'Congo', 'iso3' => 'COG', 'numcode' => '178', 'phonecode' => '242'),
            array('id' => '50', 'iso' => 'CD', 'name' => 'جمهورية الكونغو الديمقراطية', 'nicename' => 'Congo, the Democratic Republic of the', 'iso3' => 'COD', 'numcode' => '180', 'phonecode' => '242'),
            array('id' => '51', 'iso' => 'CK', 'name' => 'جزر كوك', 'nicename' => 'Cook Islands', 'iso3' => 'COK', 'numcode' => '184', 'phonecode' => '682'),
            array('id' => '52', 'iso' => 'CR', 'name' => 'كوستاريكا', 'nicename' => 'Costa Rica', 'iso3' => 'CRI', 'numcode' => '188', 'phonecode' => '506'),
            array('id' => '53', 'iso' => 'CI', 'name' => 'ساحل العاج', 'nicename' => 'Cote D\'Ivoire', 'iso3' => 'CIV', 'numcode' => '384', 'phonecode' => '225'),
            array('id' => '54', 'iso' => 'HR', 'name' => 'كرواتيا', 'nicename' => 'Croatia', 'iso3' => 'HRV', 'numcode' => '191', 'phonecode' => '385'),
            array('id' => '55', 'iso' => 'CU', 'name' => 'كوبا', 'nicename' => 'Cuba', 'iso3' => 'CUB', 'numcode' => '192', 'phonecode' => '53'),
            array('id' => '56', 'iso' => 'CY', 'name' => 'قبرص', 'nicename' => 'Cyprus', 'iso3' => 'CYP', 'numcode' => '196', 'phonecode' => '357'),
            array('id' => '57', 'iso' => 'CZ', 'name' => 'الجمهورية التشيكية', 'nicename' => 'Czech Republic', 'iso3' => 'CZE', 'numcode' => '203', 'phonecode' => '420'),
            array('id' => '58', 'iso' => 'DK', 'name' => 'الدنمارك', 'nicename' => 'Denmark', 'iso3' => 'DNK', 'numcode' => '208', 'phonecode' => '45'),
            array('id' => '59', 'iso' => 'DJ', 'name' => 'جيبوتي', 'nicename' => 'Djibouti', 'iso3' => 'DJI', 'numcode' => '262', 'phonecode' => '253'),
            array('id' => '60', 'iso' => 'DM', 'name' => 'دومينيكا', 'nicename' => 'Dominica', 'iso3' => 'DMA', 'numcode' => '212', 'phonecode' => '1767'),
            array('id' => '61', 'iso' => 'DO', 'name' => 'جمهورية الدومنيكان', 'nicename' => 'Dominican Republic', 'iso3' => 'DOM', 'numcode' => '214', 'phonecode' => '1809'),
            array('id' => '62', 'iso' => 'EC', 'name' => 'الاكوادور', 'nicename' => 'Ecuador', 'iso3' => 'ECU', 'numcode' => '218', 'phonecode' => '593'),
            array('id' => '63', 'iso' => 'EG', 'name' => 'مصر', 'nicename' => 'Egypt', 'iso3' => 'EGY', 'numcode' => '818', 'phonecode' => '20'),
            array('id' => '64', 'iso' => 'SV', 'name' => 'السلفادور', 'nicename' => 'El Salvador', 'iso3' => 'SLV', 'numcode' => '222', 'phonecode' => '503'),
            array('id' => '65', 'iso' => 'GQ', 'name' => 'غينيا الإستوائية', 'nicename' => 'Equatorial Guinea', 'iso3' => 'GNQ', 'numcode' => '226', 'phonecode' => '240'),
            array('id' => '66', 'iso' => 'ER', 'name' => 'إريتريا', 'nicename' => 'Eritrea', 'iso3' => 'ERI', 'numcode' => '232', 'phonecode' => '291'),
            array('id' => '67', 'iso' => 'EE', 'name' => 'إستونيا', 'nicename' => 'Estonia', 'iso3' => 'EST', 'numcode' => '233', 'phonecode' => '372'),
            array('id' => '68', 'iso' => 'ET', 'name' => 'أثيوبيا', 'nicename' => 'Ethiopia', 'iso3' => 'ETH', 'numcode' => '231', 'phonecode' => '251'),
            array('id' => '69', 'iso' => 'FK', 'name' => 'جزر فوكلاند', 'nicename' => 'Falkland Islands (Malvinas)', 'iso3' => 'FLK', 'numcode' => '238', 'phonecode' => '500'),
            array('id' => '70', 'iso' => 'FO', 'name' => 'جزر فاروس', 'nicename' => 'Faroe Islands', 'iso3' => 'FRO', 'numcode' => '234', 'phonecode' => '298'),
            array('id' => '71', 'iso' => 'FJ', 'name' => 'فيجي ', 'nicename' => 'Fiji', 'iso3' => 'FJI', 'numcode' => '242', 'phonecode' => '679'),
            array('id' => '72', 'iso' => 'FI', 'name' => 'فنلندا', 'nicename' => 'Finland', 'iso3' => 'FIN', 'numcode' => '246', 'phonecode' => '358'),
            array('id' => '73', 'iso' => 'FR', 'name' => 'فرنسا', 'nicename' => 'France', 'iso3' => 'FRA', 'numcode' => '250', 'phonecode' => '33'),
            array('id' => '74', 'iso' => 'GF', 'name' => 'غيانا الفرنسية', 'nicename' => 'French Guiana', 'iso3' => 'GUF', 'numcode' => '254', 'phonecode' => '594'),
            array('id' => '75', 'iso' => 'PF', 'name' => 'بولينيزيا الفرنسية', 'nicename' => 'French Polynesia', 'iso3' => 'PYF', 'numcode' => '258', 'phonecode' => '689'),
            array('id' => '76', 'iso' => 'TF', 'name' => 'المناطق الجنوبية لفرنسا', 'nicename' => 'French Southern Territories', 'iso3' => NULL, 'numcode' => NULL, 'phonecode' => '0'),
            array('id' => '77', 'iso' => 'GA', 'name' => 'جابون', 'nicename' => 'Gabon', 'iso3' => 'GAB', 'numcode' => '266', 'phonecode' => '241'),
            array('id' => '78', 'iso' => 'GM', 'name' => 'غامبيا', 'nicename' => 'Gambia', 'iso3' => 'GMB', 'numcode' => '270', 'phonecode' => '220'),
            array('id' => '79', 'iso' => 'GE', 'name' => 'جورجيا', 'nicename' => 'Georgia', 'iso3' => 'GEO', 'numcode' => '268', 'phonecode' => '995'),
            array('id' => '80', 'iso' => 'DE', 'name' => 'ألمانيا', 'nicename' => 'Germany', 'iso3' => 'DEU', 'numcode' => '276', 'phonecode' => '49'),
            array('id' => '81', 'iso' => 'GH', 'name' => 'غانا', 'nicename' => 'Ghana', 'iso3' => 'GHA', 'numcode' => '288', 'phonecode' => '233'),
            array('id' => '82', 'iso' => 'GI', 'name' => 'جبل طارق', 'nicename' => 'Gibraltar', 'iso3' => 'GIB', 'numcode' => '292', 'phonecode' => '350'),
            array('id' => '83', 'iso' => 'GR', 'name' => 'اليونان', 'nicename' => 'Greece', 'iso3' => 'GRC', 'numcode' => '300', 'phonecode' => '30'),
            array('id' => '84', 'iso' => 'GL', 'name' => 'الأرض الخضراء', 'nicename' => 'Greenland', 'iso3' => 'GRL', 'numcode' => '304', 'phonecode' => '299'),
            array('id' => '85', 'iso' => 'GD', 'name' => 'غرينادا', 'nicename' => 'Grenada', 'iso3' => 'GRD', 'numcode' => '308', 'phonecode' => '1473'),
            array('id' => '86', 'iso' => 'GP', 'name' => 'غوادلوب', 'nicename' => 'Guadeloupe', 'iso3' => 'GLP', 'numcode' => '312', 'phonecode' => '590'),
            array('id' => '87', 'iso' => 'GU', 'name' => 'غوام', 'nicename' => 'Guam', 'iso3' => 'GUM', 'numcode' => '316', 'phonecode' => '1671'),
            array('id' => '88', 'iso' => 'GT', 'name' => 'جواتيمالا', 'nicename' => 'Guatemala', 'iso3' => 'GTM', 'numcode' => '320', 'phonecode' => '502'),
            array('id' => '89', 'iso' => 'GN', 'name' => 'غينيا', 'nicename' => 'Guinea', 'iso3' => 'GIN', 'numcode' => '324', 'phonecode' => '224'),
            array('id' => '90', 'iso' => 'GW', 'name' => 'غينيا بيساو', 'nicename' => 'Guinea-Bissau', 'iso3' => 'GNB', 'numcode' => '624', 'phonecode' => '245'),
            array('id' => '91', 'iso' => 'GY', 'name' => 'غويانا', 'nicename' => 'Guyana', 'iso3' => 'GUY', 'numcode' => '328', 'phonecode' => '592'),
            array('id' => '92', 'iso' => 'HT', 'name' => 'هايتي', 'nicename' => 'Haiti', 'iso3' => 'HTI', 'numcode' => '332', 'phonecode' => '509'),
            array('id' => '93', 'iso' => 'HM', 'name' => 'قلب الجزيرة وجزر ماكدونالز', 'nicename' => 'Heard Island and Mcdonald Islands', 'iso3' => NULL, 'numcode' => NULL, 'phonecode' => '0'),
            array('id' => '94', 'iso' => 'VA', 'name' => 'الفاتيكان', 'nicename' => 'Holy See (Vatican City State)', 'iso3' => 'VAT', 'numcode' => '336', 'phonecode' => '39'),
            array('id' => '95', 'iso' => 'HN', 'name' => 'هندوراس', 'nicename' => 'Honduras', 'iso3' => 'HND', 'numcode' => '340', 'phonecode' => '504'),
            array('id' => '97', 'iso' => 'HU', 'name' => 'هنغاريا', 'nicename' => 'Hungary', 'iso3' => 'HUN', 'numcode' => '348', 'phonecode' => '36'),
            array('id' => '98', 'iso' => 'IS', 'name' => 'أيسلندا', 'nicename' => 'Iceland', 'iso3' => 'ISL', 'numcode' => '352', 'phonecode' => '354'),
            array('id' => '99', 'iso' => 'IN', 'name' => 'الهند', 'nicename' => 'India', 'iso3' => 'IND', 'numcode' => '356', 'phonecode' => '91'),
            array('id' => '100', 'iso' => 'ID', 'name' => 'إندونيسيا', 'nicename' => 'Indonesia', 'iso3' => 'IDN', 'numcode' => '360', 'phonecode' => '62'),
            array('id' => '101', 'iso' => 'IR', 'name' => 'إيران, ISLAMIC REPUBLIC OF', 'nicename' => 'Iran, Islamic Republic of', 'iso3' => 'IRN', 'numcode' => '364', 'phonecode' => '98'),
            array('id' => '102', 'iso' => 'IQ', 'name' => 'العراق', 'nicename' => 'Iraq', 'iso3' => 'IRQ', 'numcode' => '368', 'phonecode' => '964'),
            array('id' => '103', 'iso' => 'IE', 'name' => 'إيرلندا', 'nicename' => 'Ireland', 'iso3' => 'IRL', 'numcode' => '372', 'phonecode' => '353'),
            array('id' => '105', 'iso' => 'IT', 'name' => 'إيطاليا', 'nicename' => 'Italy', 'iso3' => 'ITA', 'numcode' => '380', 'phonecode' => '39'),
            array('id' => '106', 'iso' => 'JM', 'name' => 'جامايكا', 'nicename' => 'Jamaica', 'iso3' => 'JAM', 'numcode' => '388', 'phonecode' => '1876'),
            array('id' => '107', 'iso' => 'JP', 'name' => 'اليابان', 'nicename' => 'Japan', 'iso3' => 'JPN', 'numcode' => '392', 'phonecode' => '81'),
            array('id' => '108', 'iso' => 'JO', 'name' => 'الأردن', 'nicename' => 'Jordan', 'iso3' => 'JOR', 'numcode' => '400', 'phonecode' => '962'),
            array('id' => '109', 'iso' => 'KZ', 'name' => 'كازاخستان', 'nicename' => 'Kazakhstan', 'iso3' => 'KAZ', 'numcode' => '398', 'phonecode' => '7'),
            array('id' => '110', 'iso' => 'KE', 'name' => 'كينيا', 'nicename' => 'Kenya', 'iso3' => 'KEN', 'numcode' => '404', 'phonecode' => '254'),
            array('id' => '111', 'iso' => 'KI', 'name' => 'كيريباتي', 'nicename' => 'Kiribati', 'iso3' => 'KIR', 'numcode' => '296', 'phonecode' => '686'),
            array('id' => '112', 'iso' => 'KP', 'name' => 'كوريا، الجمهورية الشعبية الديمقراطية', 'nicename' => 'Korea, Democratic People\'s Republic of', 'iso3' => 'PRK', 'numcode' => '408', 'phonecode' => '850'),
            array('id' => '113', 'iso' => 'KR', 'name' => 'جمهورية كوريا', 'nicename' => 'Korea, Republic of', 'iso3' => 'KOR', 'numcode' => '410', 'phonecode' => '82'),
            array('id' => '114', 'iso' => 'KW', 'name' => 'الكويت', 'nicename' => 'Kuwait', 'iso3' => 'KWT', 'numcode' => '414', 'phonecode' => '965'),
            array('id' => '115', 'iso' => 'KG', 'name' => 'قرغيزستان', 'nicename' => 'Kyrgyzstan', 'iso3' => 'KGZ', 'numcode' => '417', 'phonecode' => '996'),
            array('id' => '116', 'iso' => 'LA', 'name' => 'جمهورية لاو الديمقراطية الشعبية', 'nicename' => 'Lao People\'s Democratic Republic', 'iso3' => 'LAO', 'numcode' => '418', 'phonecode' => '856'),
            array('id' => '117', 'iso' => 'LV', 'name' => 'لاتفيا', 'nicename' => 'Latvia', 'iso3' => 'LVA', 'numcode' => '428', 'phonecode' => '371'),
            array('id' => '118', 'iso' => 'LB', 'name' => 'لبنان', 'nicename' => 'Lebanon', 'iso3' => 'LBN', 'numcode' => '422', 'phonecode' => '961'),
            array('id' => '119', 'iso' => 'LS', 'name' => 'ليسوتو', 'nicename' => 'Lesotho', 'iso3' => 'LSO', 'numcode' => '426', 'phonecode' => '266'),
            array('id' => '120', 'iso' => 'LR', 'name' => 'ليبيريا', 'nicename' => 'Liberia', 'iso3' => 'LBR', 'numcode' => '430', 'phonecode' => '231'),
            array('id' => '121', 'iso' => 'LY', 'name' => 'الجماهيرية العربية الليبية', 'nicename' => 'Libyan Arab Jamahiriya', 'iso3' => 'LBY', 'numcode' => '434', 'phonecode' => '218'),
            array('id' => '122', 'iso' => 'LI', 'name' => 'ليختنشتاين', 'nicename' => 'Liechtenstein', 'iso3' => 'LIE', 'numcode' => '438', 'phonecode' => '423'),
            array('id' => '123', 'iso' => 'LT', 'name' => 'ليثوانيا', 'nicename' => 'Lithuania', 'iso3' => 'LTU', 'numcode' => '440', 'phonecode' => '370'),
            array('id' => '124', 'iso' => 'LU', 'name' => 'لوكسمبورغ', 'nicename' => 'Luxembourg', 'iso3' => 'LUX', 'numcode' => '442', 'phonecode' => '352'),
            array('id' => '125', 'iso' => 'MO', 'name' => 'ماكاو', 'nicename' => 'Macao', 'iso3' => 'MAC', 'numcode' => '446', 'phonecode' => '853'),
            array('id' => '126', 'iso' => 'MK', 'name' => 'مقدونيا ، جمهورية يوغسلاف السابقة', 'nicename' => 'Macedonia, the Former Yugoslav Republic of', 'iso3' => 'MKD', 'numcode' => '807', 'phonecode' => '389'),
            array('id' => '127', 'iso' => 'MG', 'name' => 'مدغشقر', 'nicename' => 'Madagascar', 'iso3' => 'MDG', 'numcode' => '450', 'phonecode' => '261'),
            array('id' => '128', 'iso' => 'MW', 'name' => 'ملاوي', 'nicename' => 'Malawi', 'iso3' => 'MWI', 'numcode' => '454', 'phonecode' => '265'),
            array('id' => '129', 'iso' => 'MY', 'name' => 'ماليزيا', 'nicename' => 'Malaysia', 'iso3' => 'MYS', 'numcode' => '458', 'phonecode' => '60'),
            array('id' => '130', 'iso' => 'MV', 'name' => 'جزر المالديف', 'nicename' => 'Maldives', 'iso3' => 'MDV', 'numcode' => '462', 'phonecode' => '960'),
            array('id' => '131', 'iso' => 'ML', 'name' => 'مالي', 'nicename' => 'Mali', 'iso3' => 'MLI', 'numcode' => '466', 'phonecode' => '223'),
            array('id' => '132', 'iso' => 'MT', 'name' => 'مالطا', 'nicename' => 'Malta', 'iso3' => 'MLT', 'numcode' => '470', 'phonecode' => '356'),
            array('id' => '133', 'iso' => 'MH', 'name' => 'جزر مارشال', 'nicename' => 'Marshall Islands', 'iso3' => 'MHL', 'numcode' => '584', 'phonecode' => '692'),
            array('id' => '134', 'iso' => 'MQ', 'name' => 'مارتينيك', 'nicename' => 'Martinique', 'iso3' => 'MTQ', 'numcode' => '474', 'phonecode' => '596'),
            array('id' => '135', 'iso' => 'MR', 'name' => 'موريتانيا', 'nicename' => 'Mauritania', 'iso3' => 'MRT', 'numcode' => '478', 'phonecode' => '222'),
            array('id' => '136', 'iso' => 'MU', 'name' => 'موريشيوس', 'nicename' => 'Mauritius', 'iso3' => 'MUS', 'numcode' => '480', 'phonecode' => '230'),
            array('id' => '137', 'iso' => 'YT', 'name' => 'مايوت', 'nicename' => 'Mayotte', 'iso3' => NULL, 'numcode' => NULL, 'phonecode' => '269'),
            array('id' => '138', 'iso' => 'MX', 'name' => 'المكسيك', 'nicename' => 'Mexico', 'iso3' => 'MEX', 'numcode' => '484', 'phonecode' => '52'),
            array('id' => '139', 'iso' => 'FM', 'name' => 'ميكرونيسيا ', 'nicename' => 'Micronesia, Federated States of', 'iso3' => 'FSM', 'numcode' => '583', 'phonecode' => '691'),
            array('id' => '140', 'iso' => 'MD', 'name' => 'جمهورية مولدوفا', 'nicename' => 'Moldova, Republic of', 'iso3' => 'MDA', 'numcode' => '498', 'phonecode' => '373'),
            array('id' => '141', 'iso' => 'MC', 'name' => 'موناكو', 'nicename' => 'Monaco', 'iso3' => 'MCO', 'numcode' => '492', 'phonecode' => '377'),
            array('id' => '142', 'iso' => 'MN', 'name' => 'منغوليا', 'nicename' => 'Mongolia', 'iso3' => 'MNG', 'numcode' => '496', 'phonecode' => '976'),
            array('id' => '143', 'iso' => 'MS', 'name' => 'مونتسيرات', 'nicename' => 'Montserrat', 'iso3' => 'MSR', 'numcode' => '500', 'phonecode' => '1664'),
            array('id' => '144', 'iso' => 'MA', 'name' => 'المغرب', 'nicename' => 'Morocco', 'iso3' => 'MAR', 'numcode' => '504', 'phonecode' => '212'),
            array('id' => '145', 'iso' => 'MZ', 'name' => 'موزامبيق', 'nicename' => 'Mozambique', 'iso3' => 'MOZ', 'numcode' => '508', 'phonecode' => '258'),
            array('id' => '146', 'iso' => 'MM', 'name' => 'ميانمار', 'nicename' => 'Myanmar', 'iso3' => 'MMR', 'numcode' => '104', 'phonecode' => '95'),
            array('id' => '147', 'iso' => 'NA', 'name' => 'ناميبيا', 'nicename' => 'Namibia', 'iso3' => 'NAM', 'numcode' => '516', 'phonecode' => '264'),
            array('id' => '148', 'iso' => 'NR', 'name' => 'ناورو', 'nicename' => 'Nauru', 'iso3' => 'NRU', 'numcode' => '520', 'phonecode' => '674'),
            array('id' => '149', 'iso' => 'NP', 'name' => 'النيبال', 'nicename' => 'Nepal', 'iso3' => 'NPL', 'numcode' => '524', 'phonecode' => '977'),
            array('id' => '150', 'iso' => 'NL', 'name' => 'هولندا', 'nicename' => 'Netherlands', 'iso3' => 'NLD', 'numcode' => '528', 'phonecode' => '31'),
            array('id' => '151', 'iso' => 'AN', 'name' => 'جزر الأنتيل الهولندية', 'nicename' => 'Netherlands Antilles', 'iso3' => 'ANT', 'numcode' => '530', 'phonecode' => '599'),
            array('id' => '152', 'iso' => 'NC', 'name' => 'كاليدونيا الجديدة', 'nicename' => 'New Caledonia', 'iso3' => 'NCL', 'numcode' => '540', 'phonecode' => '687'),
            array('id' => '153', 'iso' => 'NZ', 'name' => 'نيوزيلاندا', 'nicename' => 'New Zealand', 'iso3' => 'NZL', 'numcode' => '554', 'phonecode' => '64'),
            array('id' => '154', 'iso' => 'NI', 'name' => 'نيكاراغوا', 'nicename' => 'Nicaragua', 'iso3' => 'NIC', 'numcode' => '558', 'phonecode' => '505'),
            array('id' => '155', 'iso' => 'NE', 'name' => 'النيجر', 'nicename' => 'Niger', 'iso3' => 'NER', 'numcode' => '562', 'phonecode' => '227'),
            array('id' => '156', 'iso' => 'NG', 'name' => 'نيجيريا', 'nicename' => 'Nigeria', 'iso3' => 'NGA', 'numcode' => '566', 'phonecode' => '234'),
            array('id' => '157', 'iso' => 'NU', 'name' => 'نيوي', 'nicename' => 'Niue', 'iso3' => 'NIU', 'numcode' => '570', 'phonecode' => '683'),
            array('id' => '158', 'iso' => 'NF', 'name' => 'جزيرة نورفولك', 'nicename' => 'Norfolk Island', 'iso3' => 'NFK', 'numcode' => '574', 'phonecode' => '672'),
            array('id' => '159', 'iso' => 'MP', 'name' => 'جزر ماريانا الشمالية', 'nicename' => 'Northern Mariana Islands', 'iso3' => 'MNP', 'numcode' => '580', 'phonecode' => '1670'),
            array('id' => '160', 'iso' => 'NO', 'name' => 'النرويج', 'nicename' => 'Norway', 'iso3' => 'NOR', 'numcode' => '578', 'phonecode' => '47'),
            array('id' => '161', 'iso' => 'OM', 'name' => 'عمان', 'nicename' => 'Oman', 'iso3' => 'OMN', 'numcode' => '512', 'phonecode' => '968'),
            array('id' => '162', 'iso' => 'PK', 'name' => 'باكستان', 'nicename' => 'Pakistan', 'iso3' => 'PAK', 'numcode' => '586', 'phonecode' => '92'),
            array('id' => '163', 'iso' => 'PW', 'name' => 'بالاو', 'nicename' => 'Palau', 'iso3' => 'PLW', 'numcode' => '585', 'phonecode' => '680'),
            array('id' => '164', 'iso' => 'PS', 'name' => 'فلسطين', 'nicename' => 'Palestine', 'iso3' => NULL, 'numcode' => NULL, 'phonecode' => '970'),
            array('id' => '165', 'iso' => 'PA', 'name' => 'بنما', 'nicename' => 'Panama', 'iso3' => 'PAN', 'numcode' => '591', 'phonecode' => '507'),
            array('id' => '166', 'iso' => 'PG', 'name' => 'بابوا غينيا الجديدة', 'nicename' => 'Papua New Guinea', 'iso3' => 'PNG', 'numcode' => '598', 'phonecode' => '675'),
            array('id' => '167', 'iso' => 'PY', 'name' => 'باراغواي', 'nicename' => 'Paraguay', 'iso3' => 'PRY', 'numcode' => '600', 'phonecode' => '595'),
            array('id' => '168', 'iso' => 'PE', 'name' => 'بيرو', 'nicename' => 'Peru', 'iso3' => 'PER', 'numcode' => '604', 'phonecode' => '51'),
            array('id' => '169', 'iso' => 'PH', 'name' => 'فيلبيني', 'nicename' => 'Philippines', 'iso3' => 'PHL', 'numcode' => '608', 'phonecode' => '63'),
            array('id' => '170', 'iso' => 'PN', 'name' => 'بيتكيرن', 'nicename' => 'Pitcairn', 'iso3' => 'PCN', 'numcode' => '612', 'phonecode' => '0'),
            array('id' => '171', 'iso' => 'PL', 'name' => 'بولندا', 'nicename' => 'Poland', 'iso3' => 'POL', 'numcode' => '616', 'phonecode' => '48'),
            array('id' => '172', 'iso' => 'PT', 'name' => 'البرتغال', 'nicename' => 'Portugal', 'iso3' => 'PRT', 'numcode' => '620', 'phonecode' => '351'),
            array('id' => '173', 'iso' => 'PR', 'name' => 'بورتوريكو', 'nicename' => 'Puerto Rico', 'iso3' => 'PRI', 'numcode' => '630', 'phonecode' => '1787'),
            array('id' => '174', 'iso' => 'QA', 'name' => 'قطر', 'nicename' => 'Qatar', 'iso3' => 'QAT', 'numcode' => '634', 'phonecode' => '974'),
            array('id' => '175', 'iso' => 'RE', 'name' => 'ريونيون', 'nicename' => 'Reunion', 'iso3' => 'REU', 'numcode' => '638', 'phonecode' => '262'),
            array('id' => '176', 'iso' => 'RO', 'name' => 'رومانيا', 'nicename' => 'Romania', 'iso3' => 'ROM', 'numcode' => '642', 'phonecode' => '40'),
            array('id' => '177', 'iso' => 'RU', 'name' => 'روسيا', 'nicename' => 'Russian Federation', 'iso3' => 'RUS', 'numcode' => '643', 'phonecode' => '70'),
            array('id' => '178', 'iso' => 'RW', 'name' => 'رواندا', 'nicename' => 'Rwanda', 'iso3' => 'RWA', 'numcode' => '646', 'phonecode' => '250'),
            array('id' => '179', 'iso' => 'SH', 'name' => 'سانت هيلينا', 'nicename' => 'Saint Helena', 'iso3' => 'SHN', 'numcode' => '654', 'phonecode' => '290'),
            array('id' => '180', 'iso' => 'KN', 'name' => 'سانت كيتس ونيفيس', 'nicename' => 'Saint Kitts and Nevis', 'iso3' => 'KNA', 'numcode' => '659', 'phonecode' => '1869'),
            array('id' => '181', 'iso' => 'LC', 'name' => 'سانت لوسيا', 'nicename' => 'Saint Lucia', 'iso3' => 'LCA', 'numcode' => '662', 'phonecode' => '1758'),
            array('id' => '182', 'iso' => 'PM', 'name' => 'سانت بيير وميكلون', 'nicename' => 'Saint Pierre and Miquelon', 'iso3' => 'SPM', 'numcode' => '666', 'phonecode' => '508'),
            array('id' => '183', 'iso' => 'VC', 'name' => 'سانت فنسنت وجزر غرينادين', 'nicename' => 'Saint Vincent and the Grenadines', 'iso3' => 'VCT', 'numcode' => '670', 'phonecode' => '1784'),
            array('id' => '184', 'iso' => 'WS', 'name' => 'ساموا', 'nicename' => 'Samoa', 'iso3' => 'WSM', 'numcode' => '882', 'phonecode' => '684'),
            array('id' => '185', 'iso' => 'SM', 'name' => 'سان مارينو', 'nicename' => 'San Marino', 'iso3' => 'SMR', 'numcode' => '674', 'phonecode' => '378'),
            array('id' => '186', 'iso' => 'ST', 'name' => 'ساو تومي وبرينسيبي', 'nicename' => 'Sao Tome and Principe', 'iso3' => 'STP', 'numcode' => '678', 'phonecode' => '239'),
            array('id' => '187', 'iso' => 'SA', 'name' => 'المملكة العربية السعودية', 'nicename' => 'Saudi Arabia', 'iso3' => 'SAU', 'numcode' => '682', 'phonecode' => '966'),
            array('id' => '188', 'iso' => 'SN', 'name' => 'السنغال', 'nicename' => 'Senegal', 'iso3' => 'SEN', 'numcode' => '686', 'phonecode' => '221'),
            array('id' => '190', 'iso' => 'SC', 'name' => 'سيشل', 'nicename' => 'Seychelles', 'iso3' => 'SYC', 'numcode' => '690', 'phonecode' => '248'),
            array('id' => '191', 'iso' => 'SL', 'name' => 'سيراليون', 'nicename' => 'Sierra Leone', 'iso3' => 'SLE', 'numcode' => '694', 'phonecode' => '232'),
            array('id' => '192', 'iso' => 'SG', 'name' => 'سنغافورة', 'nicename' => 'Singapore', 'iso3' => 'SGP', 'numcode' => '702', 'phonecode' => '65'),
            array('id' => '193', 'iso' => 'SK', 'name' => 'سلوفاكيا', 'nicename' => 'Slovakia', 'iso3' => 'SVK', 'numcode' => '703', 'phonecode' => '421'),
            array('id' => '194', 'iso' => 'SI', 'name' => 'سلوفينيا', 'nicename' => 'Slovenia', 'iso3' => 'SVN', 'numcode' => '705', 'phonecode' => '386'),
            array('id' => '195', 'iso' => 'SB', 'name' => 'جزر سليمان', 'nicename' => 'Solomon Islands', 'iso3' => 'SLB', 'numcode' => '90', 'phonecode' => '677'),
            array('id' => '196', 'iso' => 'SO', 'name' => 'الصومال', 'nicename' => 'Somalia', 'iso3' => 'SOM', 'numcode' => '706', 'phonecode' => '252'),
            array('id' => '197', 'iso' => 'ZA', 'name' => 'جنوب أفريقيا', 'nicename' => 'South Africa', 'iso3' => 'ZAF', 'numcode' => '710', 'phonecode' => '27'),
            array('id' => '198', 'iso' => 'GS', 'name' => 'جورجيا الجنوبية وجزر ساندويتش الجنوبية', 'nicename' => 'South Georgia and the South Sandwich Islands', 'iso3' => NULL, 'numcode' => NULL, 'phonecode' => '0'),
            array('id' => '199', 'iso' => 'ES', 'name' => 'إسبانيا', 'nicename' => 'Spain', 'iso3' => 'ESP', 'numcode' => '724', 'phonecode' => '34'),
            array('id' => '200', 'iso' => 'LK', 'name' => 'سيريلانكا', 'nicename' => 'Sri Lanka', 'iso3' => 'LKA', 'numcode' => '144', 'phonecode' => '94'),
            array('id' => '201', 'iso' => 'SD', 'name' => 'السودان', 'nicename' => 'Sudan', 'iso3' => 'SDN', 'numcode' => '736', 'phonecode' => '249'),
            array('id' => '202', 'iso' => 'SR', 'name' => 'سورينام', 'nicename' => 'Suriname', 'iso3' => 'SUR', 'numcode' => '740', 'phonecode' => '597'),
            array('id' => '203', 'iso' => 'SJ', 'name' => 'سفالبارد ويان ماين', 'nicename' => 'Svalbard and Jan Mayen', 'iso3' => 'SJM', 'numcode' => '744', 'phonecode' => '47'),
            array('id' => '204', 'iso' => 'SZ', 'name' => 'سوازيلاند', 'nicename' => 'Swaziland', 'iso3' => 'SWZ', 'numcode' => '748', 'phonecode' => '268'),
            array('id' => '205', 'iso' => 'SE', 'name' => 'السويد', 'nicename' => 'Sweden', 'iso3' => 'SWE', 'numcode' => '752', 'phonecode' => '46'),
            array('id' => '206', 'iso' => 'CH', 'name' => 'سويسرا', 'nicename' => 'Switzerland', 'iso3' => 'CHE', 'numcode' => '756', 'phonecode' => '41'),
            array('id' => '207', 'iso' => 'SY', 'name' => 'سوريا', 'nicename' => 'Syrian Arab Republic', 'iso3' => 'SYR', 'numcode' => '760', 'phonecode' => '963'),
            array('id' => '208', 'iso' => 'TW', 'name' => 'تايوان', 'nicename' => 'Taiwan, Province of China', 'iso3' => 'TWN', 'numcode' => '158', 'phonecode' => '886'),
            array('id' => '209', 'iso' => 'TJ', 'name' => 'طاجيكستان', 'nicename' => 'Tajikistan', 'iso3' => 'TJK', 'numcode' => '762', 'phonecode' => '992'),
            array('id' => '210', 'iso' => 'TZ', 'name' => 'جمهورية تنزانيا المتحدة', 'nicename' => 'Tanzania, United Republic of', 'iso3' => 'TZA', 'numcode' => '834', 'phonecode' => '255'),
            array('id' => '211', 'iso' => 'TH', 'name' => 'تايلاند', 'nicename' => 'Thailand', 'iso3' => 'THA', 'numcode' => '764', 'phonecode' => '66'),
            array('id' => '212', 'iso' => 'TL', 'name' => 'تيمور ليستي', 'nicename' => 'Timor-Leste', 'iso3' => NULL, 'numcode' => NULL, 'phonecode' => '670'),
            array('id' => '213', 'iso' => 'TG', 'name' => 'توجو', 'nicename' => 'Togo', 'iso3' => 'TGO', 'numcode' => '768', 'phonecode' => '228'),
            array('id' => '214', 'iso' => 'TK', 'name' => 'توكيلاو', 'nicename' => 'Tokelau', 'iso3' => 'TKL', 'numcode' => '772', 'phonecode' => '690'),
            array('id' => '215', 'iso' => 'TO', 'name' => 'تونغا', 'nicename' => 'Tonga', 'iso3' => 'TON', 'numcode' => '776', 'phonecode' => '676'),
            array('id' => '216', 'iso' => 'TT', 'name' => 'ترينيداد وتوباغو', 'nicename' => 'Trinidad and Tobago', 'iso3' => 'TTO', 'numcode' => '780', 'phonecode' => '1868'),
            array('id' => '217', 'iso' => 'TN', 'name' => 'تونس', 'nicename' => 'Tunisia', 'iso3' => 'TUN', 'numcode' => '788', 'phonecode' => '216'),
            array('id' => '218', 'iso' => 'TR', 'name' => 'تركيا', 'nicename' => 'Turkey', 'iso3' => 'TUR', 'numcode' => '792', 'phonecode' => '90'),
            array('id' => '219', 'iso' => 'TM', 'name' => 'تركمانستان', 'nicename' => 'Turkmenistan', 'iso3' => 'TKM', 'numcode' => '795', 'phonecode' => '7370'),
            array('id' => '220', 'iso' => 'TC', 'name' => 'جزر تركس وكايكوس', 'nicename' => 'Turks and Caicos Islands', 'iso3' => 'TCA', 'numcode' => '796', 'phonecode' => '1649'),
            array('id' => '221', 'iso' => 'TV', 'name' => 'توفالو', 'nicename' => 'Tuvalu', 'iso3' => 'TUV', 'numcode' => '798', 'phonecode' => '688'),
            array('id' => '222', 'iso' => 'UG', 'name' => 'أوغندا', 'nicename' => 'Uganda', 'iso3' => 'UGA', 'numcode' => '800', 'phonecode' => '256'),
            array('id' => '223', 'iso' => 'UA', 'name' => 'أوكرانيا', 'nicename' => 'Ukraine', 'iso3' => 'UKR', 'numcode' => '804', 'phonecode' => '380'),
            array('id' => '224', 'iso' => 'AE', 'name' => 'الإمارات العربية المتحدة', 'nicename' => 'United Arab Emirates', 'iso3' => 'ARE', 'numcode' => '784', 'phonecode' => '971'),
            array('id' => '225', 'iso' => 'GB', 'name' => 'المملكة المتحدة', 'nicename' => 'United Kingdom', 'iso3' => 'GBR', 'numcode' => '826', 'phonecode' => '44'),
            array('id' => '226', 'iso' => 'US', 'name' => 'الولايات المتحدة الأمريكية', 'nicename' => 'United States', 'iso3' => 'USA', 'numcode' => '840', 'phonecode' => '1'),
            array('id' => '227', 'iso' => 'UM', 'name' => 'جزر الولايات المتحدة البعيدة الصغرى', 'nicename' => 'United States Minor Outlying Islands', 'iso3' => NULL, 'numcode' => NULL, 'phonecode' => '1'),
            array('id' => '228', 'iso' => 'UY', 'name' => 'أوروغواي', 'nicename' => 'Uruguay', 'iso3' => 'URY', 'numcode' => '858', 'phonecode' => '598'),
            array('id' => '229', 'iso' => 'UZ', 'name' => 'أوزبيكستان', 'nicename' => 'Uzbekistan', 'iso3' => 'UZB', 'numcode' => '860', 'phonecode' => '998'),
            array('id' => '230', 'iso' => 'VU', 'name' => 'فانواتو', 'nicename' => 'Vanuatu', 'iso3' => 'VUT', 'numcode' => '548', 'phonecode' => '678'),
            array('id' => '231', 'iso' => 'VE', 'name' => 'فنزويلا', 'nicename' => 'Venezuela', 'iso3' => 'VEN', 'numcode' => '862', 'phonecode' => '58'),
            array('id' => '232', 'iso' => 'VN', 'name' => 'فيتنام', 'nicename' => 'Viet Nam', 'iso3' => 'VNM', 'numcode' => '704', 'phonecode' => '84'),
            array('id' => '233', 'iso' => 'VG', 'name' => 'جزر فيرجن البريطانية', 'nicename' => 'Virgin Islands, British', 'iso3' => 'VGB', 'numcode' => '92', 'phonecode' => '1284'),
            array('id' => '234', 'iso' => 'VI', 'name' => 'جزر فيرجن ، الولايات المتحدة', 'nicename' => 'Virgin Islands, U.s.', 'iso3' => 'VIR', 'numcode' => '850', 'phonecode' => '1340'),
            array('id' => '235', 'iso' => 'WF', 'name' => 'واليس وفوتونا', 'nicename' => 'Wallis and Futuna', 'iso3' => 'WLF', 'numcode' => '876', 'phonecode' => '681'),
            array('id' => '236', 'iso' => 'EH', 'name' => 'الصحراء الغربية', 'nicename' => 'Western Sahara', 'iso3' => 'ESH', 'numcode' => '732', 'phonecode' => '212'),
            array('id' => '237', 'iso' => 'YE', 'name' => 'اليمن', 'nicename' => 'Yemen', 'iso3' => 'YEM', 'numcode' => '887', 'phonecode' => '967'),
            array('id' => '238', 'iso' => 'ZM', 'name' => 'زامبيا', 'nicename' => 'Zambia', 'iso3' => 'ZMB', 'numcode' => '894', 'phonecode' => '260'),
            array('id' => '239', 'iso' => 'ZW', 'name' => 'زمب ـ ابوي', 'nicename' => 'Zimbabwe', 'iso3' => 'ZWE', 'numcode' => '716', 'phonecode' => '263'),
            array('id' => '240', 'iso' => 'RS', 'name' => 'صربيا', 'nicename' => 'Serbia', 'iso3' => 'SRB', 'numcode' => '688', 'phonecode' => '381'),
            array('id' => '241', 'iso' => 'AP', 'name' => 'منطقة آسيا والمحيط الهادئ', 'nicename' => 'Asia / Pacific Region', 'iso3' => '0', 'numcode' => '0', 'phonecode' => '0'),
            array('id' => '242', 'iso' => 'ME', 'name' => 'مونتينيغرو', 'nicename' => 'Montenegro', 'iso3' => 'MNE', 'numcode' => '499', 'phonecode' => '382'),
            array('id' => '243', 'iso' => 'AX', 'name' => 'جزر آلاند', 'nicename' => 'Aland Islands', 'iso3' => 'ALA', 'numcode' => '248', 'phonecode' => '358'),
            array('id' => '245', 'iso' => 'CW', 'name' => 'كوراساو', 'nicename' => 'Curacao', 'iso3' => 'CUW', 'numcode' => '531', 'phonecode' => '599'),
            array('id' => '246', 'iso' => 'GG', 'name' => 'جيرنسي', 'nicename' => 'Guernsey', 'iso3' => 'GGY', 'numcode' => '831', 'phonecode' => '44'),
            array('id' => '247', 'iso' => 'IM', 'name' => 'جزيرة آيل أوف مان', 'nicename' => 'Isle of Man', 'iso3' => 'IMN', 'numcode' => '833', 'phonecode' => '44'),
            array('id' => '248', 'iso' => 'JE', 'name' => 'جيرسي', 'nicename' => 'Jersey', 'iso3' => 'JEY', 'numcode' => '832', 'phonecode' => '44'),
            array('id' => '249', 'iso' => 'XK', 'name' => 'كوسوفو', 'nicename' => 'Kosovo', 'iso3' => '---', 'numcode' => '0', 'phonecode' => '381'),
            array('id' => '250', 'iso' => 'BL', 'name' => 'سانت بارتيليمي', 'nicename' => 'Saint Barthelemy', 'iso3' => 'BLM', 'numcode' => '652', 'phonecode' => '590'),
            array('id' => '252', 'iso' => 'SX', 'name' => 'سينت مارتن', 'nicename' => 'Sint Maarten', 'iso3' => 'SXM', 'numcode' => '534', 'phonecode' => '1'),
            array('id' => '253', 'iso' => 'SS', 'name' => 'جنوب السودان', 'nicename' => 'South Sudan', 'iso3' => 'SSD', 'numcode' => '728', 'phonecode' => '211')
        );

        DB::table('countries')->insert($countries);
    }
    }

